### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock2#10]
Some buttons don't match their text and translation:

 - "Disable Theming" button has "Disable" translation:
![screen shot 2015-12-29 at 11 31 40 am](https://cloud.githubusercontent.com/assets/2175645/12032328/c7eb4d68-ae1f-11e5-837d-3bc19f380a95.png)

 - "Reset" button has "Reset cDock" translation:
![screen shot 2015-12-29 at 11 31 00 am](https://cloud.githubusercontent.com/assets/2175645/12032318/aac26028-ae1f-11e5-8f68-f48c2480e57c.png)

**Comment by w0lfschild** [comment]
Yup it should just say reset. I wanted it out of the way and less likely to be accidentally clicked.

It will look proper in the next release. Thanks for the heads up.

**Comment by w0lfschild** [comment]
Also right now the up down arrows do nothing. Not sure when I'll have those working or more specific formatter for each input box instead of just 999.99 max because the default formatter didn't seem to work.

Next release should have all the dock settings working and enabled though. Probably a couple more small UI tweaks as well, think I want a restart button on the theme page as well as the disable button moved over there. Means I'll probably have to adjust the height of the window and maybe move things around.

I'd also like to get some translations again so maybe I'll add a button in the title bar or something asking for translation help.
