### ISSUE TITLE
cDock and Mojave

### ISSUE THREAD

**Issue by kenm22** [w0lfschild/cDock2#131]
Tried cDock 1.1.2 with Mojave Public Betas 1 and 2. Unfortunately it requires SIP to remain disabled in order to run. I deleted all cDock and SIMBL files and did a clean installation, but the problem persisted and is repeatable. Disable SIP and cDock works fine. Enable SIP and it won’t run.

I also tried mySIMBL with the same results.

Thanks.

Ken

**Comment by w0lfschild** [comment]
Unfortunately it's something that there likely won't be any way around.

Same deal for TotalFinder https://totalfinder.binaryage.com/sip

If there ever is a workaround found I'll add it but I assume the chances are slim.

**Comment by kenm22** [comment]
Apple seems to be getting more and more restrictive. I guess it’s understandable considering the rate of hacking these days. I long for the old days when we really could modify things. ResEdit with OS 9 and earlier comes to mind.

What about becoming an identified developer? Would that work, or wouldn’t Apple allow the intrusion into the OS even if you did so?

Thanks for the response and a great product. Maybe you’ll get lucky and find a solution. I hope so.

**Comment by w0lfschild** [comment]
I actually am an identified developer (pay $100 a year). All my apps (cDock, mySIMBL, DarkBoot) are signed with my Dev account.

They are simply blocking connections from anything not signed specifically by Apple:

`skipped scripting addition "/System/Library/ScriptingAdditions/SIMBL.osax" because it is not signed by Apple.`

In fact there's a bug they introduced in Mojave Beta 3 that broke `Show in Finder` in any application that is not sandboxed:

`Since sending application [sess=100007 pid=4785 uid:501,501,501 g:20,20 pV:4786] is not permitted to send this AppleEvent to this process, returning an errAEEventNotPermitted reply.`

**Comment by kenm22** [comment]
Thanks Wolfgang.

I sent feedback to Apple. for whatever it's worth (zero?). It seems as though security has become the primary consideration these days, so much so that users can't even get their work done. What good is a computer if you can't use it to do what you need to do? We all need and want security but if it destroys the usefulness of the product then it's throwing out the baby with the bathwater.

Users need to be personally responsible and not do dumb things. I guess that's asking too much.

Again, thank you for a great product and hopefully down the road you'll stumble upon a solution.

Best Regards,

Ken

**Comment by w0lfschild** [comment]
Unfortunately that's the way it looks. Even with SIP partly disabled with just `csrutil enable --without debug` you can't inject code into another process on Mojave.

**Comment by fabiobfava** [comment]
> I actually am an identified developer (pay $100 a year). All my apps (cDock, mySIMBL, DarkBoot) are signed with my Dev account.
> 
> They are simply blocking connections from anything not signed specifically by Apple:
> 
> `skipped scripting addition "/System/Library/ScriptingAdditions/SIMBL.osax" because it is not signed by Apple.`
> 
> In fact there's a bug they introduced in Mojave Beta 3 that broke `Show in Finder` in any application that is not sandboxed:
> 
> `Since sending application [sess=100007 pid=4785 uid:501,501,501 g:20,20 pV:4786] is not permitted to send this AppleEvent to this process, returning an errAEEventNotPermitted reply.`

Hello Wolfgang, can you see any solution for cDock to Autoload on Login? Does it worth to keep the hope?

**Comment by osxest** [comment]
@w0lfschild 
Please see https://stackoverflow.com/questions/51470121/mac-os-is-there-any-way-to-sniff-system-open-call-without-kernel
"Even with a kernel extension, hooking syscalls is no longer viable due to various protections in the kernel, such as KASLR. With Mojave, code injection will no longer be viable due to SIP. The only supported method to do what's being asked is to use the Kernel Authorisation (KAuth) framework."
Will this help?
