### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock2#15]

**Comment by w0lfschild** [comment]
Checking the color this way would be affected by the wallpaper showing through the menubar. If we were to use that color then the dock wouldn't match because the wallpaper underneath the dock would add more color thus making it not match the menubar.

The only way this seems like a good idea is if the user doesn't want transparency in which case we already know the rgb colors are:
```
 37,  37,  37 (Dark)
250, 250, 250 (Standard)
```

Would probably be easier to just check if the user is in light or dark mode and change color based on that.

Here's the code for getting the color of some pixel space though:
``` objective-c
CGDirectDisplayID displayForPoint;
CGImageRef image = CGDisplayCreateImageForRect(displayForPoint, CGRectMake(2, 2, 1, 1));
NSBitmapImageRep *bitmap = [[NSBitmapImageRep alloc] initWithCGImage:image];
NSColor *color = [bitmap colorAtX:0 y:0];
NSLog(@"%@", color);
```

**Comment by dkfiresky** [comment]
I mean we can get the color without menubar `frost layer`. And then apply that color to the dock, like that feature in ubuntu, when dock & top panel matches with current wallpaper.
