### ISSUE TITLE
Two cDock Issues

### ISSUE THREAD

**Issue by scottyofeden** [w0lfschild/cDock2#193]
Two issues. First, just downloaded Mojave. Was asked to pay $4.99 for cDock, even though I had already paid for it on High Sierra. Was this a necessary purchase, or should my license been transferred over? If the first, am I able to get a refund?

Second, when making adjustments to how the dock will display, no changes are made. I have restarted my computer, I have disabled 'csrutil' and double checked the status that it is disabled, and I applied and restarted the dock in cDock. I've even restarted the computer again. No changes to the dock.

Thanks for your help.

**Comment by scottyofeden** [comment]
* Going back into the program I'm noticing making any changes in "Customize" doesn't have any effect. However, making any changes in "Dock Settings", and then selecting 'Apply Changes and Restart' does work. What I want is to get back my transparent dock. But again, making any changes to the Themes in Customize has no effect. Thanks!

**Comment by locojohn** [comment]
I confirm that I am having exactly the same issue.  Once I change anything in "Dock Settings" and restart the dock, all changes made in "Customize" section will be applied, but not before.

In addition, when I run cDock.app, I am getting "cDock Helper cannot be opened because of a problem.".   Maybe this is unrelated, though.
