### ISSUE TITLE
cDock 11.4 not rendering icons on the dock correctly

### ISSUE THREAD

**Issue by jb30** [w0lfschild/cDock2#36]
cDock 11.4 is rendering all icons on the dock in shadow.  Only active application icons are normal.  Running OS 10.11.6

![screen shot 2016-08-26 at 9 58 31 pm](https://cloud.githubusercontent.com/assets/21271673/18024433/4369ed52-6bd8-11e6-9b02-d89ade92b57b.png)

**Comment by JayBrown** [comment]
Actually I think this looks great. Wasn't this a planned option anyway?

**Comment by JayBrown** [comment]
Just tested it; it contains a bug: when you hover over the icons of apps not running, they switch to default brightness again and stay that way. When you quit a running app, its icon turns dim, which is neat, but as soon as you hover over the icon, it turns bright again. (OS X 10.11.6)

But it looks promising, for sure. I just believe that folder (i.e. true directory) icons which are not bundle (app) icons, shouldn't be dimmed, because they can't be active or inactive like an application or other bundle (like a VM). The only exception could be the Trash folder icon. If it's empty, it's dimmed, if there's content, it's bright.

**Comment by JayBrown** [comment]
You could also invert the mouse-over behavior: standard would be mouse over > bright-to-dim, inverted would be mouse-over > dim-to-bright

**Comment by herbs** [comment]
I'm also seeing that but also, on a reboot cDock is no longer working; I get the standard (ugly) Dock. Has SIMBL been updated? I'm running El Capitan, OS X 10.11.6.

**Comment by ili-codes** [comment]
Any way to fix this?

**Comment by herbs** [comment]
> On Aug 27, 2016, at 8:16 AM, Iliyan D. <notifications@github.com> wrote:
> 
> Any way to fix this?
> 

Howdy,

Interestingly, when I open cDock I always get a request for an admin password for cDockHelper. I'd expect that's relevant.

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by herbs** [comment]
The change on mouseover is temporary. If you open an app and the quite it the icon goes dark.

I fixed the complete non-operation by going through the usual rigmarole of turning off SIP, rebooting and giving my password to get the OS to let cDockHelper to run, turning SIP back on and rebooting again. Of course now I'm back to the problem of the darkened app icons in the Dock.

**Comment by herbs** [comment]
@JayBrown: If it was an option I'd turn it OFF; I have a fairly dark Desktop and like the brightness of the icons against that desktop through a transparent Dock. I can hardly make out the icons against my Desktop. And, as you mentioned it isn't even working correctly for what you want.

**Comment by herbs** [comment]
Sigh... I just went back to 0.11.3 which works perfectly well with El Capitan and Yosemite (what I have on my systems). Under El Capitan I again had to disable SIP, run cDock and give permissions for cDockHelper to run and then enable SIP. All is running just fine again. Looking forward to 0.11.5; which I hope comes out soon. Maybe I'll check back here before installing it though. :-)

**Comment by w0lfschild** [comment]
Working on getting an update out soon.

**Comment by JayBrown** [comment]
@herbs I have a pretty dark desktop as well (dark gray), but that's precisely why bright icons in the Dock annoy me. I'm also running HazeOver, i.e. only the frontmost window is bright, the rest is dimmed, and also MenuEclipse, i.e. the menu bar is dimmed too most of the time. I like to focus, concentrate on what I'm working on, and I don't want bright & shiny stuff outside stealing that focus. But here we're entering the taste territory: some users will like this approach, other will like the default GUI. Both are fine.

Come to think of it: @w0lfschild … another option, instead of dimming closed/inactive apps (or in addition to dimming), is to desaturate the icons, remove all the color, i.e. have black&white (or rather grayscale) icons for closed/inactive apps (dimmed or not), and only icons of active apps have color. (Don't know if that's possible, though.)

**Comment by herbs** [comment]
> On Aug 27, 2016, at 6:47 PM, Joss Brown <notifications@github.com> wrote:
> 
> @herbs I have a pretty dark desktop as well (dark gray), but that's precisely why bright icons in the Dock annoy me. I'm also running HazeOver, i.e. only the frontmost window is bright, the rest is dimmed, and also MenuEclipse, i.e. the menu bar is dimmed too most of the time. I like to focus, concentrate on what I'm working on, and I don't want bright & shiny stuff outside stealing that focus. But here we're entering the taste territory: some users will like this approach, other will like the default GUI. Both are fine.
> 
> Come to think of it: @w0lfschild … another option, instead of dimming closed/inactive apps (or in addition to dimming), is to desaturate the icons, remove all the color, i.e. have black&white (or rather grayscale) icons for closed/inactive apps (dimmed or not), and only icons of active apps have color. (Don't know if that's possible, though.)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howdy,

Why not hide the Dock if it is too bothersome?

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by w0lfschild** [comment]
Okay I put out 0.12.1 hopefully that should fix things up.

**Comment by ptcox** [comment]
0.12.1 is working fine for me under 10.11.6. Thanks for the quick fix of 0.11.4! (I needed to go through the csrutil disable/enable gymnastics again, but I'm getting good at it.)

**Comment by herbs** [comment]
> On Aug 27, 2016, at 9:53 PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> Okay I put out 0.12.1 hopefully that should fix things up.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howdy,

Thanks for the very quick work in getting 0.12.0 out so quickly! It works fine.

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)
