### ISSUE TITLE
Pb after El capitan migration :'(

### ISSUE THREAD

**Issue by 2y2d** [w0lfschild/cDock2#4]
Here is the message I Have :

[img]http://i.imgur.com/v1PXIJY.png[/img]

Definitively I DON'T want restore !!!

Any other way ?
How can I Full cDock previous version desinstallation,…

**Comment by dkfiresky** [comment]
@2y2d
- (1) If you want cDock 2 to work just complete the steps shown on your picture.
- (2) If you want to remove cDock 2, complete step 3, and simply remove the application from your Applications folder.
- (3) If you want to restore your dock to the defaults, click `Preferences -> Reset Dock`

**Comment by liam4** [comment]
Too bad.. due to the way CDock works you'll have to follow the instructions. But don't worry! You won't remove any of the data on your computer. All you're doing is disabling System Integrity Protection. All your things will still be there, as long as you only run the command in the picture and don't do anything else.

**Comment by johnkdoe** [comment]
is the way it works w.r.t. System Integrity Protection a one time thing (i.e. can i 'csrutil disable' once, run cDock2 to get it set up, and then perform a 'csrutil enable' to get back to the security level  is trying to provide?

**Comment by dkfiresky** [comment]
@johnkdoe you need to disable S.I.P. only for SIMBL installation, so simply install cDock 2 and you may enable S.I.P again, everything should work fine and it should be possible to change themes etc.

**Comment by w0lfschild** [comment]
This is not an issue, just a requirement of using the app on 10.11
