### ISSUE TITLE
Handoff

### ISSUE THREAD

**Issue by sdaitzman** [w0lfschild/cDock2#66]
Handoff does not function for me while using cDock.

**Comment by w0lfschild** [comment]
I'm guessing the issue is unrelated but happened around the time you installed cDock.

cDock doesn't do anything that would affect Handoff working or not working.

![screen shot 2017-12-01 at 11 55 45 pm](https://user-images.githubusercontent.com/1920148/33513225-3a42d482-d6f3-11e7-99d5-90c1ec645053.png)

**Comment by sdaitzman** [comment]
@w0lfschild maybe it was something else! I'll keep looking into it.
