### ISSUE TITLE
Change Finder icon position in dock

### ISSUE THREAD

**Issue by zhanggang807** [w0lfschild/cDock2#86]
can cDock2 do this?

**Comment by JayBrown** [comment]
At some point I stumbled across a tool that can *hide* the Finder icon in the Dock, but it didn't fully work. But in principle that tells me that you can (maybe) move the Finder in the Dock. But with cDock? Probably not.

You might want to try something different, namely this old method of substituting Finder, but I can't say if it still works on current macOS/OSX systems:

```
defaults write com.apple.loginwindow Finder /Applications/AlternateApplication.app
```

With that you can set a different login application as a substitute for Finder, e.g. TextEdit:

```
defaults write com.apple.loginwindow Finder /Applications/TextEdit.app
```

Then, after login, TextEdit (or any other app you specifiy) is supposed to auto-launch instead of Finder, and Finder itself is supposed to register as just another application that you can launch and quit like any other app. So you need to put Finder in your user's login items in System Preferences, otherwise you have to launch it manually. But I haven't tested this method, so I can't say if it still works on current systems, and if yes, if the Finder icon in the Dock is actually movable.

**Comment by w0lfschild** [comment]
Hmm I know how to remove it but not re-order it. It's probably possible but not something I know how to do now. Same goes for the Trash can.

**Comment by zhanggang807** [comment]
@w0lfschild  how to re-order it ??
