### ISSUE TITLE
No 3D 

### ISSUE THREAD

**Issue by usego1** [w0lfschild/cDock2#91]
I just update to 1.02 and Paid  but the 3 D no Work on the Dock ! Version before 1 Work !  I jhave theme 3d Ligth  whit personal colors , but others in 3d Dont work also !  OS is 10.13.3

thanks for your help !

**Comment by w0lfschild** [comment]
Make sure you have the settings correctly applied.

<img width="1109" alt="screen shot 2018-03-18 at 9 44 56 am" src="https://user-images.githubusercontent.com/1920148/37623366-aff54cd6-2b81-11e8-9aff-c8a69cb23d2f.png">

**Comment by GitTheHellOutaHere** [comment]
Agreed - included 3D themes **DO NOT WORK.**

The only theme I liked was 3D Clean.

**Finder vanished from my dock!**
Fortunately I use Path Finder, but where’d Finder go? I need it occasionally.

That emoji theme is WILD! (can’t imagine anyone using it though).

**Reverting to last version now.**


Other issues:
Since when is dark grey considered vibrant?
Checking the  "vibrant window" box makes the window the _opposite_ of vibrant.
**Vibrant:** (of color) bright and striking.

Almost black is NOT bright and striking.

In Dock Settings, Dock is misspelled as Doc twice.

**Comment by GitTheHellOutaHere** [comment]
After reverting, got my 3D theme back and Finder is back in place.

**Comment by w0lfschild** [comment]
@GitTheHellOutaHere  

I understand that you're salty about the update but at least have some base to your complaints.

> Agreed - included 3D themes DO NOT WORK.

I changed the .plist structure in the latest version. The included themes work fine but legacy themes from older version won't work without some manual setup. However this is something I feel like I could make automated at some point.  

> Finder vanished from my dock!

A new option that can be turned on or off.

> Checking the "vibrant window" box makes the window the opposite of vibrant. It’s a dark theme, just call it that.

Actually it depends on if you have the "dark menubar and dock" setting on in system preferences, it uses the same styles. The word "Vibrant" is referring to the name Apple uses for the appearances [NSAppearanceNameVibrantDark](https://developer.apple.com/documentation/appkit/nsappearancenamevibrantdark?language=objc) and [NSAppearanceNameVibrantLight](https://developer.apple.com/documentation/appkit/nsappearancenamevibrantlight?language=objc) which are used.

> In Dock Settings, Dock is misspelled twice as Doc.

That's actually supposed to be Doc. short for Documents just like I use App. short for Applications directly above it. App spacers are in the left/top half of the Dock, Doc spacers are in the right/bottom half.

**Comment by GitTheHellOutaHere** [comment]
There was basis.

The included 3D themes DON’T WORK without additional and unmentioned "manual setup."
Not sure what "manual setup" means, and to my knowledge no instructions were provided.

If you bought a piece of software and it didn’t work correctly, then the developer told you it _will work_ - all you have to do is figure out how to manually reconfigure it on your own because they’re not saying WHAT needs tweaking or HOW to accomplish it, you probably wouldn’t be very satisfied and would likely demand a refund because you paid for WORKING software, not a project.

I don’t script, I don’t code, and I don’t fiddle with plist or config files unless explicit instructions are given, including the requisite text or commands I can copy/paste.

At first I just thought it was improperly tested and released prematurely, but your answer makes it clear that you were aware of these issues before it was released and chose not to do anything about it.

Frankly, the only difference from the last version I saw, aside from more themes I’ll never use, is the window layout is redesigned. I can’t even say it’s improved, just...redesigned.

But then I didn’t spend a lot of time using it once my theme and Finder vanished.
I did look for a "Remove Finder" setting but didn’t see one - apparently didn’t look hard enough since you say it’s there.

FWIW I _do_ have dark menu bar and Dock enabled.

My error I for misunderstanding the use of the word "Doc."
I though it meant _Dock_ spacers. 
I’m aware docs can be placed at at the right side - I have one Pages doc and one text file there now.

w0lfschild, I’m not bashing your app - I'm grateful it’s being maintained.
As I’ve stated before, Crapple’s Dock is hideous!

I like the 3D Clean theme and I don’t have to cringe every time I unhide the Dock.

I look forward to continued improvement, though I’m not sure what needs improving.
Version 0.12.2 is working fine - even better than the latest, so why should folks pay for an "upgrade"  other than to send some $ your way as incentive to keep the project going?

I didn’t notice any terrific new features worth paying for, but don’t mind a contribution for all your time spent on this and because the **OLD** cDock makes my computer experience more pleasurable (the new one made me frustrated).

But, if in my haste to revert to the previous version I overlooked some grand new features or improvements (other than the GUI), then by all means point 'em out for me!

BTW, why hasn’t this project been updated here on Github?
Last release was 2/5/16.
No description, release notes or screenshots for v1.0.2.

MacUpdate was umm...updated.

**Comment by w0lfschild** [comment]
By manual setup I mean manually clicking the buttons in the UI.

Here's most of what's changed from 2 to 3. I'll also be adding to version 3 over time and fixing things (assuming I can) if they break in system updates.

New

- Pinning the dock to an edge of the screen
- Show/Hide Finder tile
- Show/Hide Trash tile
- Show/Hide AirDrop icon in Dock
- Show/Hide iCloud Drive icon in Dock
- Show/Hide Launchpad new item dot
- Launchpad adjust row and column count
- Show item count badge on Trash tile
- Color icon badges background
- Color application switcher background
- Color Mission Control background
- Badges and label text will change to be readable based on background color
- Control some default Dock settings without restarting the Dock
- More options for showing icon reflections
- Dim inactive icons
- Small spacer tiles
- Pick your own images for dock and indicator backgrounds (.png format)
- Add or Remove themes without restarting cDock
- Option to automatically expand spaces when entering Mission Control
- New themes
- Updated SIMBLManger
- Crash protection (in case a macOS update causes repeated Dock crashing)
- Save and restore from dock packups
- Button to restore dock to default
- Built in error reporting, crash reporting and feedback

Fixes

- Unhandled exception when trying to use non RGBA color picker
- Issue where switching themes back and forth would decrease slider values
- Issue where Left / Right position dock could draw custom indicator images incorrectly
- Dock crash when switching between some themes
- 3D option not working in some cases
- Issue with Vertical Full screen dock and magnification enabled not reaching end of screen
- Label background not fully applying on folder views
- Some changes to themes not applying until Dock restart
- Better Dock reloading
- Better Dock layering (Badge > Icon > Indicator > Reflection)
- Issues with reduced transparency enabled
- Helper Application is now CodeSigned

**Comment by usego1** [comment]
lates version still no Work ! I wonder for what i paid for 3 Version ? 2 Version work for me !
look at the sreen shoot thats all active and only active App Icon is in USE !
BUT Color dock or no 3 D Dock !!!!!!!!
HELP !! restart of dock dont Help !!! where i find old Version ??
![cdock](https://user-images.githubusercontent.com/14293549/39083505-1d21a1c2-4565-11e8-9e39-f3b290a84989.jpeg)

**Comment by w0lfschild** [comment]
@usego1  Try deleting the cDock theme folder `~/Library/Application Support/cDock/themes` then restarting cDock and the Dock.

Old versions can be found here: https://github.com/w0lfschild/app_updates/tree/master/cDock

**Comment by usego1** [comment]
Newest version 1.4 cdock von mojave 14.1 beta still no 3 D dock !! Thanks for your help
